/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FormAdmin;

import Service.StaticService;
import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author ranco
 */
public class Statistical extends javax.swing.JPanel {

    /**
     * Creates new form Statistical
     */
    public Statistical() {
        initComponents();
        showBarChart();
        showPieChart();
        showLineChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        showBarChart();
        showPieChart();
        showLineChart();
    }//GEN-LAST:event_formFocusGained

    public void showBarChart(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        StaticService num = new StaticService();
        dataset.setValue(num.getTotalREvenuebyMonth(1), "Amount", "Jan");
        dataset.setValue(num.getTotalREvenuebyMonth(2), "Amount", "Feb");
        dataset.setValue(num.getTotalREvenuebyMonth(3), "Amount", "Mar");
        dataset.setValue(num.getTotalREvenuebyMonth(4), "Amount", "Apr");
        dataset.setValue(num.getTotalREvenuebyMonth(5), "Amount", "May");
        dataset.setValue(num.getTotalREvenuebyMonth(6), "Amount", "June");
        dataset.setValue(num.getTotalREvenuebyMonth(7), "Amount", "July");
        dataset.setValue(num.getTotalREvenuebyMonth(8), "Amount", "Aug");
        dataset.setValue(num.getTotalREvenuebyMonth(9), "Amount", "Sept");
        dataset.setValue(num.getTotalREvenuebyMonth(10), "Amount", "Oct");
        dataset.setValue(num.getTotalREvenuebyMonth(11), "Amount", "Nov");
        dataset.setValue(num.getTotalREvenuebyMonth(12), "Amount", "Dec");
        
        JFreeChart chart = ChartFactory.createBarChart("Income statements","Monthly","amount", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        //categoryPlot.setRangeGridlinePaint(Color.BLUE);
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(204,0,51);
        renderer.setSeriesPaint(0, clr3);
        
        ChartPanel barpChartPanel = new ChartPanel(chart);
        jPanel1.removeAll();
        jPanel1.add(barpChartPanel, BorderLayout.CENTER);
        jPanel1.validate();
        
        
    }
    
    public void showPieChart(){
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset( );
      StaticService num = new StaticService();
      barDataset.setValue( "Total Income" , num.getTotalREvenue());  
      barDataset.setValue( "Total Outcome" , num.getTotalDes());
      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("Profit",barDataset, true,true,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
        piePlot.setSectionPaint("Total Outcome", new Color(102,255,102));
        piePlot.setSectionPaint("Total Income", new Color(255,102,153));
      
       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        jPanel2.removeAll();
        jPanel2.add(barChartPanel, BorderLayout.CENTER);
        jPanel2.validate();
    }
    
    public void showLineChart(){
        //create dataset for the graph
         DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        StaticService num = new StaticService();
        dataset.setValue(num.getTotalChiByMonth(1), "Amount", "Jan");
        dataset.setValue(num.getTotalChiByMonth(2), "Amount", "Feb");
        dataset.setValue(num.getTotalChiByMonth(3), "Amount", "Mar");
        dataset.setValue(num.getTotalChiByMonth(4), "Amount", "Apr");
        dataset.setValue(num.getTotalChiByMonth(5), "Amount", "May");
        dataset.setValue(num.getTotalChiByMonth(6), "Amount", "June");
        dataset.setValue(num.getTotalChiByMonth(7), "Amount", "July");
        dataset.setValue(num.getTotalChiByMonth(8), "Amount", "Aug");
        dataset.setValue(num.getTotalChiByMonth(9), "Amount", "Sept");
        dataset.setValue(num.getTotalChiByMonth(10), "Amount", "Oct");
        dataset.setValue(num.getTotalChiByMonth(11), "Amount", "Nov");
        dataset.setValue(num.getTotalChiByMonth(12), "Amount", "Dec");
        
        //create chart
        JFreeChart linechart = ChartFactory.createLineChart("Outcome statements","Monthly","amount", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        //create plot object
         CategoryPlot lineCategoryPlot = linechart.getCategoryPlot();
       // lineCategoryPlot.setRangeGridlinePaint(Color.BLUE);
        lineCategoryPlot.setBackgroundPaint(Color.white);
        
        //create render object to change the moficy the line properties like color
        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
        Color lineChartColor = new Color(204,0,51);
        lineRenderer.setSeriesPaint(0, lineChartColor);
        
         //create chartPanel to display chart(graph)
        ChartPanel lineChartPanel = new ChartPanel(linechart);
        jPanel3.removeAll();
        jPanel3.add(lineChartPanel, BorderLayout.CENTER);
        jPanel3.validate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
