import java.sql.Connection;
import java.sql.SQLException;

public class Main {
    public static void main(String[] args) throws SQLException {
//        System.out.println("Hello world!");
        Connection connection = null;
        connection = DbConnection.getConnect();
    }
}

///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package Form;
//
//        import Connect.JDBCConnection;
//        import java.sql.Connection;
//        import java.sql.PreparedStatement;
//        import java.sql.ResultSet;
//        import java.sql.SQLException;
//        import java.util.Vector;
//        import javax.swing.JOptionPane;
//        import javax.swing.table.DefaultTableModel;
//
///**
// *
// * @author ranco
// */
//public class LichSuDangNhap extends javax.swing.JFrame {
//
//    /**
//     * Creates new form LichSuDangNhap
//     */
//    public LichSuDangNhap() {
//        initComponents();
//        setResizable(false);
//        setLocationRelativeTo(null);
//        tableModel = (DefaultTableModel) tblDanhSach.getModel();
//    }
//
//    DefaultTableModel tableModel;
//    Connection conn = null;
//    PreparedStatement pre = null;
//    ResultSet rs = null;
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        btnBack = new javax.swing.JButton();
//        btnThoat = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        tblDanhSach = new javax.swing.JTable();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            public void windowOpened(java.awt.event.WindowEvent evt) {
//                formWindowOpened(evt);
//            }
//        });
//
//        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
//
//        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
//        jLabel1.setText("Lịch sử đăng nhập");
//
//        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
//        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/backsmall.png"))); // NOI18N
//        btnBack.setText("Quay lại menu");
//        btnBack.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnBackActionPerformed(evt);
//            }
//        });
//
//        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
//        btnThoat.setText("Thoát");
//        btnThoat.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnThoatActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(28, 28, 28)
//                                .addComponent(btnBack)
//                                .addGap(182, 182, 182)
//                                .addComponent(jLabel1)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
//                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(26, 26, 26))
//        );
//        jPanel1Layout.setVerticalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(15, 15, 15)
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jLabel1)
//                                        .addComponent(btnBack))
//                                .addGap(0, 17, Short.MAX_VALUE))
//        );
//
//        tblDanhSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
//                new Object [][] {
//
//                },
//                new String [] {
//                        "Mã", "Sự kiện", "Thời gian", "Quyền truy cập"
//                }
//        ) {
//            boolean[] canEdit = new boolean [] {
//                    false, false, false, true
//            };
//
//            public boolean isCellEditable(int rowIndex, int columnIndex) {
//                return canEdit [columnIndex];
//            }
//        });
//        tblDanhSach.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
//        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                tblDanhSachMouseClicked(evt);
//            }
//        });
//        jScrollPane1.setViewportView(tblDanhSach);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(10, 10, 10)
//                                                .addComponent(jScrollPane1))
//                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        AdminForm uf = new AdminForm();
//        uf.setVisible(true);
////        uf.setMaNV(this.getMaNV().trim());
////        uf.setTenNV(this.getTenNV().trim());
//        this.dispose();
//    }
//
//    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//        System.exit(1);
//    }
//
//    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void formWindowOpened(java.awt.event.WindowEvent evt) {
//        // TODO add your handling code here:
//        try {
//            conn = JDBCConnection.getConnection();
//            String sql = "select * from LichSuDangNhap";
//            pre = conn.prepareStatement(sql);
//            rs = pre.executeQuery();
//            tableModel.setRowCount(0);
//            while (rs.next()) {
//                Vector arr = new Vector();
//                arr.add(rs.getString("maNV"));
//                arr.add(rs.getString("suKien"));
//                arr.add(rs.getString("thoiGian"));
//                arr.add(rs.getString("quyenTruyCap"));
//                tableModel.addRow(arr);
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane, ex);
//        }
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LichSuDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LichSuDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LichSuDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LichSuDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LichSuDangNhap().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton btnBack;
//    private javax.swing.JButton btnThoat;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTable tblDanhSach;
//    // End of variables declaration
//}