/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FormStaff;

import Connect.JDBCConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class History extends javax.swing.JPanel {
    private Connection connection = JDBCConnection.getConnection();
    /**
     * Creates new form History
     */
    public History() {
        initComponents();
        showHistory();
    }

    public void showHistory(){
        DefaultTableModel model = (DefaultTableModel) HistoryTable.getModel();
        model.setRowCount(0);
        try {
            String sql = "select dbo.Client.FullName, dbo.Client.Username, dbo.History.IdOrder, dbo.History.paidDate\n" +
"FROM((dbo.History INNER JOIN dbo.OrderTour ON dbo.History.IdOrder = dbo.OrderTour.IdOrder) INNER JOIN dbo.Client\n" +
"ON dbo.OrderTour.IdClient = dbo.Client.IdClient )";
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("FullName"));
                vector.add(resultSet.getString("Username"));
                vector.add(resultSet.getString("IdOrder"));
                vector.add(resultSet.getString("paidDate"));
                model.addRow(vector);                  
            }
        } catch (Exception e) {
            e.getMessage();
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        search_inputField = new javax.swing.JTextField();
        Search_btn = new javax.swing.JToggleButton();

        jLabel1.setText("Lịch sử thanh toán");

        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Fullname", "Customer Username", "Order ID", "Payment day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HistoryTable);

        Search_btn.setText("Search");
        Search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(search_inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(search_inputField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_btnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) HistoryTable.getModel();
        model.setRowCount(0);
        try {
            if (search_inputField.getText().equals("") == false) {
                System.out.println(search_inputField.getText());
                String CusUserName =  search_inputField.getText();
                Statement statement = connection.createStatement();          
                //Lấy ClientUsername
                String sql = "select dbo.Client.FullName, dbo.Client.Username, dbo.History.IdOrder, dbo.History.paidDate\n" +
"FROM((dbo.History INNER JOIN dbo.OrderTour ON dbo.History.IdOrder = dbo.OrderTour.IdOrder) INNER JOIN dbo.Client\n" +
"ON dbo.OrderTour.IdClient = dbo.Client.IdClient ) where dbo.Client.FullName = N'" + CusUserName + "'";
                System.out.println(sql);
                ResultSet resultSet = statement.executeQuery(sql);
                model.setRowCount(0);
                while (resultSet.next()) {
                    Vector vector = new Vector();
                    vector.add(resultSet.getString("FullName"));
                    vector.add(resultSet.getString("Username"));
                    vector.add(resultSet.getString("IdOrder"));
                    vector.add(resultSet.getString("paidDate"));
                    model.addRow(vector);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng, vui lòng nhập lại!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error!");
        }
    }//GEN-LAST:event_Search_btnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HistoryTable;
    private javax.swing.JToggleButton Search_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_inputField;
    // End of variables declaration//GEN-END:variables
}
