/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FormStaff;

import Connect.JDBCConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class History extends javax.swing.JPanel {
    private Connection connection = JDBCConnection.getConnection();
    /**
     * Creates new form History
     */
    public History() {
        initComponents();
        showHistory();
    }

    public void showHistory(){
        DefaultTableModel model = (DefaultTableModel) HistoryTable.getModel();
        model.setRowCount(0);
        try {
            String sql = "select dbo.Client.FullName, dbo.Client.Username, dbo.History.IdOrder, dbo.History.paidDate\n" +
"FROM((dbo.History INNER JOIN dbo.OrderTour ON dbo.History.IdOrder = dbo.OrderTour.IdOrder) INNER JOIN dbo.Client\n" +
"ON dbo.OrderTour.IdClient = dbo.Client.IdClient )";
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("FullName"));
                vector.add(resultSet.getString("Username"));
                vector.add(resultSet.getString("IdOrder"));
                vector.add(resultSet.getString("paidDate"));
                model.addRow(vector);                  
            }
        } catch (Exception e) {
            e.getMessage();
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        search_inputField = new javax.swing.JTextField();
        activeStaffLabel = new javax.swing.JLabel();
        deactivateStaffBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Fullname", "Customer Username", "Order ID", "Payment day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HistoryTable);

        activeStaffLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        activeStaffLabel.setForeground(new java.awt.Color(153, 153, 255));
        activeStaffLabel.setText("History Payment");

        deactivateStaffBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        deactivateStaffBtn.setForeground(new java.awt.Color(153, 153, 255));
        deactivateStaffBtn.setText("Search");
        deactivateStaffBtn.setBorder(new javax.swing.border.MatteBorder(null));
        deactivateStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deactivateStaffBtnMouseClicked(evt);
            }
        });
        deactivateStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateStaffBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(activeStaffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(deactivateStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(activeStaffLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deactivateStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(168, 168, 168))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deactivateStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deactivateStaffBtnMouseClicked
         // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) HistoryTable.getModel();
        model.setRowCount(0);
        try {
            if (search_inputField.getText().equals("") == false) {
                System.out.println(search_inputField.getText());
                String CusUserName =  search_inputField.getText();
                Statement statement = connection.createStatement();          
                //Lấy ClientUsername
                String sql = "select dbo.Client.FullName, dbo.Client.Username, dbo.History.IdOrder, dbo.History.paidDate\n" +
"FROM((dbo.History INNER JOIN dbo.OrderTour ON dbo.History.IdOrder = dbo.OrderTour.IdOrder) INNER JOIN dbo.Client\n" +
"ON dbo.OrderTour.IdClient = dbo.Client.IdClient ) where dbo.Client.FullName = N'" + CusUserName + "'";
                System.out.println(sql);
                ResultSet resultSet = statement.executeQuery(sql);
                model.setRowCount(0);
                while (resultSet.next()) {
                    Vector vector = new Vector();
                    vector.add(resultSet.getString("FullName"));
                    vector.add(resultSet.getString("Username"));
                    vector.add(resultSet.getString("IdOrder"));
                    vector.add(resultSet.getString("paidDate"));
                    model.addRow(vector);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng, vui lòng nhập lại!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error!");
        }
    }//GEN-LAST:event_deactivateStaffBtnMouseClicked

    private void deactivateStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateStaffBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deactivateStaffBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HistoryTable;
    private javax.swing.JLabel activeStaffLabel;
    private javax.swing.JButton deactivateStaffBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_inputField;
    // End of variables declaration//GEN-END:variables
}
